### ISSUE TITLE
zipsByProduct returning empty files

### ISSUE THREAD

**Issue by kjones13** [NEONScience/NEON-utilities#16] opened 2017-11-21 22:45 UTC
Hello!
Here is the R code I am running, attempting to download all phenology data from Harvard Forest.

```
library(devtools)
install_github("NEONScience/NEON-utilities/neonDataStackR", dependencies=TRUE)

library(neonDataStackR)
library(downloader)

dpid <- 'DP1.10055.001'
zipsByProduct(dpID=dpid, site="HARV", package="basic")
```

The result is a folder containing a zip folder for every month, each folder contains only one csv or xml file which when opened, is empty.  This does not occur when I run an api call for a single month of data or download directly from the data portal. Can you advise?

**Comment by chrlaney** [comment] 2017-11-21 23:56
Hi @kjones13 & @cklunch,

I am trying to reproduce this problem but on my Mac I can't even download a single zip file from the API using downloader::download(). For example (and note that the URLs expire after a while, so this URL won't work shortly after I post this):

```
downloader::download("https://neon-prod-pub-1.s3.data.neonscience.org/NEON.DOM.SITE.DP1.10055.001/PROV/HARV/20130801T000000--20130901T000000/basic/NEON.D01.HARV.DP1.10055.001.2013-08.basic.20170727T181808Z.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20171121T231101Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=pub-internal-read%2F20171121%2Fdata%2Fs3%2Faws4_request&X-Amz-Signature=13e595e5c4a991b16df835ba52b7966892b85af7c6a3cfbc00c95d72acf9a138", "/Users/claney/GitHub/Other/NEON-utilities/neonDataStackR/filesToStack10055/NEON.D01.HARV.DP1.10055.001.2013-08.basic.20170727T181808Z.zip")
downloaded 0 bytes

Error in download.file(url, method = method, ...) :
  cannot download all files
In addition: Warning message:
In download.file(url, method = method, ...) :
  URL 'https://neon-prod-pub-1.s3.data.neonscience.org/NEON.DOM.SITE.DP1.10055.001/PROV/HARV/20130801T000000--20130901T000000/basic/NEON.D01.HARV.DP1.10055.001.2013-08.basic.20170727T181808Z.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20171121T231101Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=pub-internal-read%2F20171121%2Fdata%2Fs3%2Faws4_request&X-Amz-Signature=13e595e5c4a991b16df835ba52b7966892b85af7c6a3cfbc00c95d72acf9a138': status was '403 Forbidden'
```
I checked in with @jzollerneon who also tested this on his mac - downloader::download() (we both have v0.4) is defaulting to libcurl and appears to be truncating the URLs. Not sure why this would suddenly start to be an issue. I haven't tried downloading the older version of downloader. Sorry to not be more helpful @cklunch.

**Comment by kjones13** [comment] 2017-11-23 00:17
@chrlaney I got this response last night and was already too late to run it, it was already to attempt it. 
When @cklunch and I were troubleshooting this issue previously, there seemed to be a difference between how macs and pcs behaved.  I too am using downloader package v0.4.

@samsimkin, would you mind running the code above and letting us know what you get? 

I'm not sure this is a new issue, I have successfully loaded data from other data products using downloader::download, but never from phenology.  Could it have anything to do with one of the tables being site-all?

**Comment by samsimkin** [comment] 2017-11-27 16:43
At Katie's request I ran her script and got the same problem she did when using the the zipsByProduct function (e.g. zipsByProduct(dpID=dpid, site="HARV", package="basic") ). That problem is that the zips that download contain just a single, seemingly random, file (sometimes a validation file, sometimes a variables file, sometimes a data file, sometimes a readme file, sometimes an xml file, but never all of them together).

**Comment by cklunch** [comment] 2017-11-27 16:49
I'll look into it. I thought I had this fixed, since I circulated a test case in October and it worked on everybody's machine, but something must have changed.

**Comment by kjones13** [comment] 2017-11-27 20:37
@cklunch I just ran the test script you sent in October, it still works for me, so I think the issue we are running into must be different.

**Comment by cklunch** [comment] 2017-11-27 22:47
@chrlaney @jzollerneon Just pushed a new zipsByProduct(), now with a mode="wb" argument in the downloader::download call. It now works on Katie's computer (Windows) and mine (Mac). Can you try it out and see if you're still running into problems? Thanks!

**Comment by chrlaney** [comment] 2017-11-27 22:54
Unfortunately your update doesn't help with the issue I'm having.
> library(devtools)
> install_github("NEONScience/NEON-utilities/neonDataStackR", dependencies=TRUE)
> library (neonDataStackR)
> zipsByProduct(dpID="DP1.10023.001", site="all", package="basic", check.size=T)
Continuing will download files totaling approximately 2.907603 MB. Do you want to proceed y/n: y
downloaded 0 bytes

Error in download.file(url, method = method, ...) : 
  cannot download all files
In addition: Warning message:
In download.file(url, method = method, ...) :
  URL 'https://neon-prod-pub-1.s3.data.neonscience.org/NEON.DOM.SITE.DP1.10023.001/PROV/ORNL/20140601T000000--20140701T000000/basic/NEON.D07.ORNL.DP1.10023.001.2014-06.basic.20170616T192659Z.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20171127T225322Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=pub-internal-read%2F20171127%2Fdata%2Fs3%2Faws4_request&X-Amz-Signature=02d3f8230f91dbffdb3a0cea58e88ab389711c312103eab5088cd0d67c13d38f': status was '403 Forbidden'

**Comment by chrlaney** [comment] 2017-11-27 22:55
But clicking on the link the error message works...

**Comment by chrlaney** [comment] 2018-01-10 17:00
This seems to no longer be an issue.

**Closed by chrlaney** 2018-01-10 17:00 UTC
